name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Linting & Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Dependencies
        run: flutter pub get

      - name: Linting
        run: flutter analyze

      - name: Formatting
        run: dart format --set-exit-if-changed .

      - name: Tests
        run: flutter test